version: 2

updates:
  - package-ecosystem: uv
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "05:00"
      timezone: America/Sao_Paulo
    target-branch: develop
    open-pull-requests-limit: 5
    groups:
      python-dependencies:
        patterns:
          - "*"
    commit-message:
      prefix: chore
      prefix-development: chore
      include: scope

  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "05:15"
      timezone: America/Sao_Paulo
    target-branch: develop
    open-pull-requests-limit: 5
    groups:
      node-dependencies:
        patterns:
          - "*"
    commit-message:
      prefix: chore
      prefix-development: chore
      include: scope

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "05:30"
      timezone: America/Sao_Paulo
    target-branch: develop
    open-pull-requests-limit: 5
    groups:
      action-dependencies:
        patterns:
          - "*"
    commit-message:
      prefix: chore
      include: scope

  - package-ecosystem: docker-compose
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "05:45"
      timezone: America/Sao_Paulo
    target-branch: develop
    open-pull-requests-limit: 5
    groups:
      compose-dependencies:
        patterns:
          - "*"
    commit-message:
      prefix: chore
      include: scope
