"""Evidence-grounded generation contracts and provider boundary."""

from prescriptive_maintenance.generation.bedrock import (
    BedrockClientFactory,
    BedrockGenerationProvider,
    BedrockProviderConfig,
    BedrockRuntimeClient,
)
from prescriptive_maintenance.generation.contracts import (
    EVIDENCE_CONFLICT_WARNING_CODE,
    EVIDENCE_GAP_WARNING_CODE,
    GENERATION_CONTRACT_VERSION,
    MAX_EVIDENCE_CONTENT_CHARACTERS,
    MAX_EVIDENCE_ITEMS,
    MAX_TOTAL_EVIDENCE_CONTENT_CHARACTERS,
    Citation,
    Diagnosis,
    DiagnosticSupport,
    DiagnosticSupportStatus,
    Evidence,
    GenerationRequest,
    GenerationResult,
    GenerationStatus,
    GenerationWarning,
    Prescription,
    ProviderOutput,
    ProviderUsage,
)
from prescriptive_maintenance.generation.prompt import (
    GENERATION_SYSTEM_PROMPT,
    GENERATION_SYSTEM_PROMPT_VERSION,
    VersionedPrompt,
    build_provider_request,
)
from prescriptive_maintenance.generation.provider import (
    FakeGenerationProvider,
    GenerationProvider,
    GenerationProviderError,
    InvalidProviderOutputError,
    ProviderConfigurationError,
    ProviderDisabledError,
    ProviderExecutionError,
    ProviderInvalidResponseError,
    ProviderRequest,
    ProviderResponse,
)
from prescriptive_maintenance.generation.service import (
    generate_prescription,
    validate_provider_output,
)

__all__ = [
    "EVIDENCE_CONFLICT_WARNING_CODE",
    "EVIDENCE_GAP_WARNING_CODE",
    "GENERATION_CONTRACT_VERSION",
    "GENERATION_SYSTEM_PROMPT",
    "GENERATION_SYSTEM_PROMPT_VERSION",
    "MAX_EVIDENCE_CONTENT_CHARACTERS",
    "MAX_EVIDENCE_ITEMS",
    "MAX_TOTAL_EVIDENCE_CONTENT_CHARACTERS",
    "BedrockClientFactory",
    "BedrockGenerationProvider",
    "BedrockProviderConfig",
    "BedrockRuntimeClient",
    "Citation",
    "Diagnosis",
    "DiagnosticSupport",
    "DiagnosticSupportStatus",
    "Evidence",
    "FakeGenerationProvider",
    "GenerationProvider",
    "GenerationProviderError",
    "GenerationRequest",
    "GenerationResult",
    "GenerationStatus",
    "GenerationWarning",
    "InvalidProviderOutputError",
    "Prescription",
    "ProviderConfigurationError",
    "ProviderDisabledError",
    "ProviderExecutionError",
    "ProviderInvalidResponseError",
    "ProviderOutput",
    "ProviderRequest",
    "ProviderResponse",
    "ProviderUsage",
    "VersionedPrompt",
    "build_provider_request",
    "generate_prescription",
    "validate_provider_output",
]
