[project]
name = "prescriptive-maintenance-api"
version = "0.1.0"
description = "Esqueleto do backend modular de manutenção prescritiva."
readme = "README.md"
authors = [
  { name = "Renan Mocelin", email = "renanryuakame@gmail.com" },
]
requires-python = ">=3.13,<3.14"
dependencies = [
  "fastapi>=0.141.1,<1.0.0",
  "pydantic-settings>=2.15.0,<3.0.0",
  "uvicorn>=0.52.4,<1.0.0",
]

[build-system]
requires = ["uv_build>=0.9.4,<0.10.0"]
build-backend = "uv_build"

[tool.uv.build-backend]
module-name = "prescriptive_maintenance"
